Machine test  Euphoria_infotech/Models/UserLogin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Machine_test__Euphoria_infotech.Models
{
    public class UserLogin
    {
        
        [Required]
        public string UserName { get; set; }
        [Required]
        public string Password { get; set; }
    
}
}

Machine test  Euphoria_infotech/Models/UserRegistation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Machine_test__Euphoria_infotech.Models
{
    public class UserRegistation
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Enter Your Name must be   Required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Enter Your Address must be   Required")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Enter Your UserName must be   Required")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Enter Your Password must be   Required")]
        public string  Password { get; set; }
        [Required(ErrorMessage = "Enter Your Role must be   Required")]
        public Role RoleName { get; set; }
        [Required(ErrorMessage = "Enter Your Age must be   Required")]
        public string  Age { get; set; }


        public enum Role
        {
                    User,
                    Admin
        }
    }
}

Machine test  Euphoria_infotech/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Machine_test__Euphoria_infotech.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Machine test  Euphoria_infotech/Controllers/UserDetailController.cs
using Machine_test__Euphoria_infotech.Models;
using Machine_test__Euphoria_infotech.Repository;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Machine_test__Euphoria_infotech.Controllers
{
    public class UserDetailController : Controller
    {
        // GET: UserDetail
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(UserRegistation userRegistratio)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UserDetailRepository userDetailRepository = new UserDetailRepository();

                    if (userDetailRepository.AddReg(userRegistratio))
                    {
                        ViewBag.Message = "Employee details added successfully";
                    }
                }

                return View();
            }
            catch
            {
                return View();
            }
        }
        [HttpGet]
        public ActionResult Login()
        {
            if (Session["LoggedInUserName"] == null)
                return View();
            else
                return RedirectToAction(nameof(AccountDetail));
        }


        [HttpPost]
        public ActionResult Login(UserLogin userLogin)
        {
            string SqlCon = ConfigurationManager.ConnectionStrings["EuphoriaDB"].ConnectionString;
            SqlConnection con = new SqlConnection(SqlCon);
            string SqlQuery = "select UserName,Password from UserRegistation where UserName=@UserName and Password=@Password";
            con.Open();
            SqlCommand cmd = new SqlCommand(SqlQuery, con);
            cmd.Parameters.AddWithValue("@UserName", userLogin.UserName);
            cmd.Parameters.AddWithValue("@Password", userLogin.Password);
            SqlDataReader sdr = cmd.ExecuteReader();
            if (sdr.Read())
            {
                Session["LoggedInUserName"] = userLogin.UserName.ToString();
                return RedirectToAction(nameof(AccountDetail));
            }
            else
            {
                ViewData["Message"] = "Login Failed, Username OR Password incorrect!!";
            }
            con.Close();
            return View();
        }

        [HttpGet]
        public ActionResult Logout()
        {
            Session["LoggedInUserName"] = null;
            Session.Clear();
            return RedirectToAction(nameof(Login));
        }

        [HttpGet]
        public ActionResult AccountDetail()
        {
            if (Session["LoggedInUserName"] != null)
            {
                DataTable dt = new DataTable();
                string SqlCon = ConfigurationManager.ConnectionStrings["EuphoriaDB"].ConnectionString;
                using (SqlConnection cn = new SqlConnection(SqlCon))
                {
                    using (SqlCommand cmd = new SqlCommand($"select Name,Address,UserName,Age from UserRegistation where UserName='{Session["LoggedInUserName"]}'"))
                    {
                        cmd.Connection = cn;
                        using (SqlDataAdapter da = new SqlDataAdapter(cmd))
                        {
                            da.Fill(dt);
                        }
                    }
                }
                return View(dt);
            }
            return RedirectToAction(nameof(Login));
        }

    }
}
       

Machine test  Euphoria_infotech/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Machine test  Euphoria_infotech/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Machine test  Euphoria_infotech/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Machine test  Euphoria_infotech/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("User Ragistation ", "Register", "UserDetail")</li>
                    @if (Session["LoggedInUserName"] != null)
                    {
                        <li>@Html.ActionLink("Logout", "Logout", "UserDetail", new { area = "" }, new { @class = "nav-link" })</li>
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Machine test  Euphoria_infotech/Views/UserDetail/AccountDetail.cshtml
@using System.Data
@model DataTable
@{
    ViewBag.Title = "AccountDetail";
}

<h2>Account Detail</h2>
<table cellpadding="5" cellspacing="5" border="1">
    <tr style="background-color:aliceblue">
        <th>Name</th>
        <th>Address</th>
        <th>UserName</th>
        <th>Age</th>
    </tr>
    @foreach (DataRow dr in Model.Rows)
    {
<tr>
    <td>@dr["Name"]</td>
    <td>@dr["Address"]</td>
    <td>@dr["UserName"]</td>
    <td>@dr["Age"]</td>


</tr>
    }
</table>

Machine test  Euphoria_infotech/Views/UserDetail/Login.cshtml
@model Machine_test__Euphoria_infotech.Models.UserLogin

@{
    ViewBag.Title = "Login";
    if (ViewData["Message"] != null)
    {
        <h3 style="color:red"><strong>@ViewData["Message"]</strong></h3>
    }
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

        <body style="background-color:darkseagreen"> 
    <div class="form-horizontal">
        <h4>UserLogin</h4>
        <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Your Username" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", type = "password",@placeholder="Enter Your Password" } })             @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-success" />
            </div>
        </div>
    </div>
</body>
}

<div>
    @Html.ActionLink("Back to Register", "Register")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Machine test  Euphoria_infotech/Views/UserDetail/Register.cshtml
@model Machine_test__Euphoria_infotech.Models.UserRegistation

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserRegistation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Login")
</div>